//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapTable
    {
        public int id { get; set; }
        public string CountryName { get; set; }
        public string Citizens { get; set; }
        public string Area { get; set; }
        public string Capital { get; set; }
        public int Time { get; set; }
    }
}
